os: linux
dist: bionic
language: python
python:
  - 3.9
  - 3.10
  - 3.11

addons:
  apt:
    packages:
      # build deps
      - swig
      # runtime deps
      - xmlsec1
      - libengine-pkcs11-openssl
      - libsofthsm2
      - softhsm2
      - opensc

install:
  - pip install pykcs11
  - pip install nose
  - pip install coveralls

script:
  - coverage run --source=xmlsec setup.py nosetests -vv -d

after_success:
  - coveralls
